name: destiny
version: 0.1.0.0
github: samarsha/destiny
author: Sarah Marshall
maintainer: sarah@sarahmarshall.name
copyright: 2020 Sarah Marshall

dependencies:
- aeson
- aeson-pretty
- base >= 4.7 && < 5
- bytestring
- directory
- elm-bridge
- extra
- file-embed
- filepath
- http-types
- mime-types
- MonadRandom
- o-clock
- optparse-applicative
- safe
- signal
- text
- uuid
- wai
- wai-websockets
- warp
- websockets

ghc-options:
- -Wall

library:
  source-dirs: server/src

executables:
  destiny-server:
    main: Main.hs
    source-dirs: server/app
    dependencies:
    - destiny
